config/routes.rb
Rails.application.routes.draw do
  root 'tv_guides#index'
  resources :tv_guides, only: [:index, :show] do
  	collection do
  	 	get :scrape
  	end 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/tv_guides_controller.rb
class TvGuidesController < ApplicationController
  def index
  	@episode = Episode.paginate(page: params[:page], per_page: 30)
  end

  def show
  	@episode = Episode.find(params[:id])
  end

  # This is the way to start the scrapping from view/browser ...where you pass the date. If other scrapping running then it will ask to wait.
  def scrape
  	if params[:date].present?
      sc = Scraping.where(status: false).count 
      if sc<1
    		if Transmitter.new.get_scrape_date.include?(params[:date])
  	  		# session[:scrape] = { start: true, date: params[:date] }
          Scraping.create({which_date: params[:date], status: false})
  	  		ScrapeJob.perform_async(params[:date])
          @msg = "Scrapping started for date #{params[:date]}."
  	  	else
          @msg = "Given date #{params[:date]} in not in scrapping range, Either past 2 days or next 5 days."
  	  		# session[:scrape] = { start: false, date: params[:date] }
  	  	end
      else
        @msg = "Scrapping running, Please wait to complete date."
      end
  	end
	  # redirect_to root_path
  end
end

app/helpers/tv_guides_helper.rb
module TvGuidesHelper
end

app/views/tv_guides/index.html.haml
.container
  
  .row
    .col{style: "float:left;"}
      %h2 Transmitter (count: #{Transmitter.count}) | Program (count: #{Program.count}) | Episode (count: #{Episode.count}) 
    .col{style: "float:right;margin-top:25px;"}
      .btn.btn-warning{"data-target" => "#initiateScrapingModal", "data-toggle" => "modal", :type => "button"} Initiate Scraping


  .row
    .col
      = will_paginate(@episode)
      
  .row
    .col
      %table.table.table-bordered
        %thead
          %tr
            %th{:scope => "col"} TV Channel
            %th{:scope => "col"} Time
            %th{:scope => "col"} P Name
            %th{:scope => "col"} P genre
            %th{:scope => "col"} P branch
            %th{:scope => "col"} Date
            %th 
        %tbody.main
          - i = 0
          - @episode.order(:created_at).each do|es|
            %tr
              %td=es.program.transmitter.name
              %td="(#{es.start_time.strftime("%H : %M")}) - (#{es.end_time.strftime("%H : %M")})"
              %td=link_to es.program.name, tv_guide_path(es)
              %td=es.program.genre
              %td=es.program.branch
              %td=es.created_at.strftime("%v")
              %th=link_to "view", tv_guide_path(es)
  .row
    .col
      = will_paginate(@episode)

#initiateScrapingModal.modal
  .modal-dialog
    = form_tag(scrape_tv_guides_path, method: :get, remote:true) do 
      .modal-content
        .modal-header
          %button.close{"data-dismiss" => "modal", :type => "button"} ×
          %h4.modal-title RE Website Data Scrape
        .modal-body
          #status{style: "display:none; width: 100%;height: 25px;background-color: lightgoldenrodyellow;text-align: center;margin-bottom: 10px;margin-top: -15px;"} ....
          = date_field_tag :date, nil, class: "form-control scrape_date",required: true
        .modal-footer
          %button.btn.btn-success{type: "submit"}  Submit
          %button.btn.btn-danger{"data-dismiss" => "modal", :type => "button"} Cancel

:css 
  .scrape_date{
    width: 140px;
    display: inline-block;
    padding: 0 0 0 12px;
    height: 35px;
  }

app/views/tv_guides/scrape.js.erb
$('#status').html("<%=@msg%>");
$('#status').show();

app/views/tv_guides/show.html.haml
.h2 Episode
%p
  =@episode.to_json

%hr
.h2 Program
%p
  =@episode.program.to_json
.h2 Transmitter
%p
  =@episode.program.transmitter.to_json

%hr
.h2 Episode Info
%p  
  =@episode.episode_infos.to_json

%hr
.h2 Rating
%p  
  =@episode.ratings.to_json
/ %ul
/   %li
/     Name =======>
/     =@episode.program.name
/   %li
/     id =======>
/     =@episode.id
/   %li
/     program_id =======>
/     =@episode.program_id
/   %li
/     program_date =======>
/     =@episode.program_date
/   %li
/     start_time =======>
/     =@episode.start_time
/   %li
/     end_time =======>
/     =@episode.end_time
/   %li
/     duration =======>
/     =@episode.duration
/   %li
/     source_url =======>
/     =@episode.source_url
/   %li
/     preview_video_url =======>
/     =@episode.preview_video_url
/   %li
/     is_scraped =======>
/     =@episode.is_scraped
/   %li
/     active =======>
/     =@episode.active
/   %li
/     created_at =======>
/     =@episode.created_at
/   %li
/     updated_at =======>
/     =@episode.updated_at